"""alert asset

Revision ID: 252d81f9d612
Revises: None
Create Date: 2016-06-25 15:45:43.636834

"""

# revision identifiers, used by Alembic.
revision = '252d81f9d612'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cmdb_asset', 'hostname',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('cmdb_asset_group', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('cmdb_idc', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'cmdb_idc', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cmdb_idc', type_='unique')
    op.alter_column('cmdb_idc', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('cmdb_asset_group', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('cmdb_asset', 'hostname',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    ### end Alembic commands ###
